spring.application.name=postgreSQL
#This will connect to the desktop pgAdmin in the localhost
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
# This will connect to the docker db
#spring.datasource.url=jdbc:postgresql://db:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update